ACTUAL_URLS = [
    'api/user/settings',
    'api/user',
    'api/user/settings/<int:role_id>',
    'api/user/settings/currency',
    'api/user/change-phone',
    'api/file/upload',
    'api/project',
    'api/project/time-entry (UPDATED)',
    'api/workers/<int:worker_id>',
    'api/project/<int:project_id>/worker',
    'api/projects/paginate',
    'api/projects',
    'api/project/<int:project_id>/set-complete',
    'api/project/<int:project_id>',
    'api/project/advance (UPDATED)',
    'api/user/login',
    'api/user/signup',
    'api/user/send-code',
    'api/user/token-renew',
    'api/user/check-code',
    'api/user/logout',
    'api/user/change-pin',
    'api/user/reset-pin',
    'api/team',
    'api/users/<int:user_id>/projects',
    'api/team/worker',
    'api/team/worker/<int:user_id>',
]
