# Generated by Django 4.0.4 on 2022-07-01 15:16

import django.db.models.deletion
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('token_data', models.TextField(blank=True, null=True, verbose_name='token')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(default='admin@admin.com', max_length=254, unique=True, verbose_name='email пользователя')),
                ('phone', models.CharField(default='+777', max_length=255, unique=True, verbose_name='Телефон пользователя')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=main.models.AppUser.user_avatar_path, verbose_name='Аватар пользователя')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография пользователя')),
                ('authority', models.IntegerField(verbose_name='Полномочия пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('budget', models.FloatField(blank=True, null=True, verbose_name='Бюджет проекта')),
                ('is_archived', models.BooleanField(verbose_name='Флаг архивности проекта')),
                ('work_time', models.FloatField(default=0, verbose_name='Общее рабочее время')),
                ('average_rate', models.FloatField(default=0, verbose_name='Средняя ставка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.appuser',
                                            verbose_name='ID Создателя')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectEmployee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Ставка рабочего')),
                ('advance', models.FloatField(blank=True, null=True, verbose_name='Размер аванса')),
                ('salary', models.FloatField(blank=True, default=0, null=True,
                                             verbose_name='Размер зп, считается автоматически')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project',
                                              verbose_name='ID Проекта')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название соц.сети')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.appuser',
                                            verbose_name='ID Создателя')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='UsersTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team',
                                           verbose_name='ID команды')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appuser',
                                           verbose_name='ID Пользователя')),
            ],
            options={
                'verbose_name': 'Связь команды с участником',
                'verbose_name_plural': 'Связи команды с участниками',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('work_time', models.FloatField(verbose_name='Выданное рабочее время')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projectemployee',
                                               verbose_name='ID Рабочего')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appuser',
                                                verbose_name='ID Инициатора')),
            ],
            options={
                'verbose_name': 'Рабочее время работника',
                'verbose_name_plural': 'Рабочие времена работников',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL')),
                ('social_network',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.socialnetwork',
                                   verbose_name='ID соц.сети')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appuser',
                                           verbose_name='ID Пользователя')),
            ],
            options={
                'verbose_name': 'Связь пользователя и социальной сети',
                'verbose_name_plural': 'Связи пользователей и социальных сетей',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание роли')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет роли HEX')),
                ('percentage', models.FloatField(blank=True, null=True, verbose_name='Доля в процентах')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Размер платы')),
                ('is_base', models.BooleanField(default=False, verbose_name='Флаг базовой роли')),
                ('type', models.IntegerField(blank=True, default=0, verbose_name='Тип роли')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appuser',
                                             verbose_name='ID Создателя роли')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='main.project', verbose_name='Проект, которому принадлежит роль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата с которой считать статистику')),
                ('end_date', models.DateField(verbose_name='Дата до которой считать статистику')),
                ('income', models.FloatField(default=0, verbose_name='Доход всех работников')),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.project',
                                              verbose_name='ID Проекта')),
            ],
            options={
                'verbose_name': 'Статистика проекта',
                'verbose_name_plural': 'Статистики проектов',
            },
        ),
        migrations.AddField(
            model_name='projectemployee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.role',
                                    verbose_name='ID Роли пользователя'),
        ),
        migrations.AddField(
            model_name='projectemployee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appuser',
                                    verbose_name='ID Пользователя'),
        ),
        migrations.CreateModel(
            name='HistoryRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Ставка рабочего')),
                ('date_change', models.DateField(auto_now=True, null=True, verbose_name='Дата внесения изменений')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projectemployee',
                                               verbose_name='ID Рабочего')),
            ],
            options={
                'verbose_name': 'История ставок работника',
                'verbose_name_plural': 'Истории ставок работников',
            },
        ),
        migrations.CreateModel(
            name='HistoryAdvance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('advance', models.FloatField(verbose_name='Размер аванса')),
                ('date_change', models.DateField(auto_now=True, null=True, verbose_name='Дата внесения изменений')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projectemployee',
                                               verbose_name='ID Рабочего')),
            ],
            options={
                'verbose_name': 'История авансов работника',
                'verbose_name_plural': 'Истории авансов работников',
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата с которой считать статистику')),
                ('end_date', models.DateField(verbose_name='Дата до которой считать статистику')),
                ('income', models.FloatField(default=0, verbose_name='Доход')),
                ('work_time', models.FloatField(default=0, verbose_name='Рабочее время')),
                ('rate', models.FloatField(default=0, verbose_name='Текущая ставка рабочего')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projectemployee',
                                               verbose_name='ID Пользователя')),
            ],
            options={
                'verbose_name': 'Статистика работника',
                'verbose_name_plural': 'Статистики работников',
            },
        ),
        migrations.CreateModel(
            name='AdvanceStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата с которой считать статистику')),
                ('end_date', models.DateField(verbose_name='Дата до которой считать статистику')),
                ('advance', models.FloatField(default=0, verbose_name='Сумма авансов работника')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projectemployee',
                                               verbose_name='ID Пользователя')),
            ],
            options={
                'verbose_name': 'Статистика аванса',
                'verbose_name_plural': 'Статистики авансов',
            },
        ),
    ]
