# Generated by Django 4.0.4 on 2022-06-19 22:57

import django.db.models.deletion
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название проекта')),
                ('proposed_income',
                 models.FloatField(blank=True, null=True, verbose_name='Предполагаемый заработок в проекте')),
                ('is_archived', models.BooleanField(verbose_name='Флаг архивности проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Project_employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Ставка рабочего')),
                ('salary', models.FloatField(verbose_name='З/П рабочего')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project',
                                                 verbose_name='ID Проекта')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название соц.сети')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email пользователя')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон пользователя')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=main.models.User.user_avatar_path,
                                             verbose_name='Аватар пользователя')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография пользователя')),
                ('authority', models.IntegerField(blank=True, null=True, verbose_name='Полномочия пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UsersTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team',
                                              verbose_name='ID команды')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user',
                                              verbose_name='ID Пользователя')),
            ],
            options={
                'verbose_name': 'Связь команды с участником',
                'verbose_name_plural': 'Связи команды с участниками',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='Дата транзакции')),
                ('type_accrual', models.CharField(
                    choices=[('SAL', 'SALARY'), ('ADV', 'ADVANCE'), ('REPAIR', 'RESPONSIBLE FOR REPAIR'),
                             ('AMORT', 'AMORTIZATION OF INSTRUMENT'), ('TIME', 'RESPONSIBLE OF TIME')], max_length=255,
                    verbose_name='Тип начисления')),
                ('amount', models.FloatField(verbose_name='Размер начисления')),
                ('employee_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project_employee',
                                   verbose_name='ID Рабочего')),
            ],
            options={
                'verbose_name': 'Начисление работника',
                'verbose_name_plural': 'Начисления работников',
            },
        ),
        migrations.CreateModel(
            name='Time_entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('work_time', models.FloatField(verbose_name='Выданное рабочее время')),
                ('employee_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project_employee',
                                   verbose_name='ID Рабочего')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user',
                                                verbose_name='ID Инициатора')),
            ],
            options={
                'verbose_name': 'Рабочее время работника',
                'verbose_name_plural': 'Рабочие времена работников',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.user',
                                    verbose_name='ID Создателя'),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('social_network_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.socialnetwork',
                                   verbose_name='ID соц.сети')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user',
                                              verbose_name='ID Пользователя')),
            ],
            options={
                'verbose_name': 'Связь пользователя и социальной сети',
                'verbose_name_plural': 'Связи пользователей и социальных сетей',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание роли')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет роли HEX')),
                ('percentage', models.FloatField(blank=True, null=True, verbose_name='Доля в процентах')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Размер платы')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user',
                                                verbose_name='ID Создателя роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.AddField(
            model_name='project_employee',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.role',
                                    verbose_name='ID Роли пользователя'),
        ),
        migrations.AddField(
            model_name='project_employee',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user',
                                    verbose_name='ID Пользователя'),
        ),
        migrations.CreateModel(
            name='Project_agregate_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project',
                                                 verbose_name='ID Проекта')),
            ],
            options={
                'verbose_name': 'Агрегатные данные проекта',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.user',
                                    verbose_name='ID Создателя'),
        ),
        migrations.CreateModel(
            name='Employee_Statistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата с которой считать статистику')),
                ('end_date', models.DateField(verbose_name='Дата до которой считать статистику')),
                ('employee_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project_employee',
                                   verbose_name='ID Пользователя')),
            ],
            options={
                'verbose_name': 'Статистика работника',
                'verbose_name_plural': 'Статистики работников',
            },
        ),
    ]
