# Generated by Django 4.0.4 on 2022-07-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectemployee',
            name='work_time',
            field=models.FloatField(default=0, verbose_name='Суммарное рабочее время'),
        ),
    ]
