# Generated by Django 4.0.4 on 2022-06-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_statistics',
            name='income',
            field=models.FloatField(default=0, verbose_name='Доход'),
        ),
        migrations.AddField(
            model_name='project',
            name='average_rate',
            field=models.FloatField(default=0, verbose_name='Средняя ставка'),
        ),
        migrations.AddField(
            model_name='project',
            name='work_time',
            field=models.FloatField(default=0, verbose_name='Общее рабочее время'),
        ),
        migrations.DeleteModel(
            name='Project_agregate_data',
        ),
    ]
