# Generated by Django 4.0.4 on 2022-10-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesTypeDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Код роли')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Тип роли',
                'verbose_name_plural': 'Типы роли',
            },
        ),
    ]
