# Generated by Django 4.0.4 on 2022-10-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rolestypedictionary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='code',
        ),
    ]
