# Generated by Django 4.0.4 on 2022-07-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_projectemployee_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='work_time',
            field=models.FloatField(default=0, null=True, verbose_name='Общее рабочее время'),
        ),
        migrations.AlterField(
            model_name='projectemployee',
            name='work_time',
            field=models.FloatField(default=0, null=True, verbose_name='Суммарное рабочее время'),
        ),
    ]
