# Generated by Django 4.0.4 on 2022-10-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.IntegerField(default=0, verbose_name='Код роли'),
        ),
    ]
