# Generated by Django 4.0.4 on 2022-06-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_time_entry_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_statistics',
            name='work_time',
            field=models.FloatField(default=0, verbose_name='Рабочее время'),
        ),
    ]
