# Generated by Django 4.0.4 on 2022-07-04 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_alter_projectemployee_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to='main.appuser',
                                         verbose_name='Участники команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner',
                                    to='main.appuser', verbose_name='ID Создателя'),
        ),
        migrations.DeleteModel(
            name='UsersTeam',
        ),
    ]
