# Generated by Django 4.0.4 on 2022-06-20 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_employee_statistics_work_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='proposed_income',
        ),
        migrations.RemoveField(
            model_name='project_employee',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='project_employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='employee_statistics',
            name='rate',
            field=models.FloatField(default=0, verbose_name='Текущая ставка рабочего'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.FloatField(blank=True, null=True, verbose_name='Бюджет проекта'),
        ),
        migrations.CreateModel(
            name='Salary_employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('salary', models.FloatField(blank=True, default=0, null=True, verbose_name='З/П рабочего')),
                ('employee_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project_employee',
                                   verbose_name='ID Рабочего')),
            ],
        ),
        migrations.CreateModel(
            name='Rate_entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Ставка рабочего')),
                ('employee_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project_employee',
                                   verbose_name='ID Рабочего')),
            ],
            options={
                'verbose_name': 'Ставка работника',
                'verbose_name_plural': 'Ставки работников',
            },
        ),
        migrations.CreateModel(
            name='Project_Statistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата с которой считать статистику')),
                ('end_date', models.DateField(verbose_name='Дата до которой считать статистику')),
                ('income', models.FloatField(default=0, verbose_name='Доход всех работников')),
                ('project_id',
                 models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.project',
                                   verbose_name='ID Проекта')),
            ],
            options={
                'verbose_name': 'Статистика проекта',
                'verbose_name_plural': 'Статистики проектов',
            },
        ),
        migrations.CreateModel(
            name='Advance_Statistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата с которой считать статистику')),
                ('end_date', models.DateField(verbose_name='Дата до которой считать статистику')),
                ('advance', models.FloatField(default=0, verbose_name='Сумма авансов работника')),
                ('employee_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project_employee',
                                   verbose_name='ID Пользователя')),
            ],
            options={
                'verbose_name': 'Статистика работника',
                'verbose_name_plural': 'Статистики работников',
            },
        ),
    ]
