# Generated by Django 4.0.4 on 2022-06-21 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_remove_project_proposed_income_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='role_employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('employee_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project_employee',
                                   verbose_name='ID Рабочего')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.role',
                                              verbose_name='ID Роли пользователя')),
            ],
            options={
                'verbose_name': 'Связь роль - работник',
                'verbose_name_plural': 'Связи роли-работники',
            },
        ),
    ]
