# Generated by Django 4.0.4 on 2022-06-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_role_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advance_statistics',
            options={'verbose_name': 'Статистика аванса', 'verbose_name_plural': 'Статистики авансов'},
        ),
        migrations.RemoveField(
            model_name='project_employee',
            name='role_id',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название роли'),
        ),
    ]
