# Generated by Django 4.0.4 on 2022-07-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_alter_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_register',
            field=models.BooleanField(default=True, verbose_name='Флаг зарегистрированого пользователя'),
        ),
    ]
