# Generated by Django 4.0.4 on 2022-06-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_alter_advance_statistics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_data',
            field=models.TextField(blank=True, null=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=254, verbose_name='email пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+777', max_length=255, verbose_name='Телефон пользователя'),
        ),
    ]
