# Generated by Django 4.0.4 on 2022-07-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_appuser_is_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(default='+777', max_length=255, null=True, unique=True,
                                   verbose_name='Телефон пользователя'),
        ),
    ]
