# Generated by Django 4.0.4 on 2022-06-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_token_data_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
