# Generated by Django 4.0.4 on 2022-06-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_social_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryAdvance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('advance', models.FloatField(verbose_name='Размер аванса')),
                ('date_change', models.DateField(auto_now=True, null=True, verbose_name='Дата внесения изменений')),
            ],
            options={
                'verbose_name': 'История авансов работника',
                'verbose_name_plural': 'Истории авансов работников',
            },
        ),
        migrations.CreateModel(
            name='HistoryRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Ставка рабочего')),
                ('date_change', models.DateField(auto_now=True, null=True, verbose_name='Дата внесения изменений')),
            ],
            options={
                'verbose_name': 'История ставок работника',
                'verbose_name_plural': 'Истории ставок работников',
            },
        ),
        migrations.CreateModel(
            name='ProjectEmployee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Ставка рабочего')),
                ('advance', models.FloatField(verbose_name='Размер аванса')),
                ('salary', models.FloatField(default=0, verbose_name='Размер зп, считается автоматически')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project', verbose_name='ID Проекта')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='ID Пользователя')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.RemoveField(
            model_name='project_employee',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='project_employee',
            name='user_id',
        ),
        migrations.RenameModel(
            old_name='role_employee',
            new_name='RoleEmployee',
        ),
        migrations.RenameModel(
            old_name='Time_entry',
            new_name='TimeEntry',
        ),
        migrations.DeleteModel(
            name='Rate_entry',
        ),
        migrations.AddField(
            model_name='historyrate',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projectemployee', verbose_name='ID Рабочего'),
        ),
        migrations.AddField(
            model_name='historyadvance',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projectemployee', verbose_name='ID Рабочего'),
        ),
        migrations.AlterField(
            model_name='advance_statistics',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projectemployee', verbose_name='ID Пользователя'),
        ),
        migrations.AlterField(
            model_name='employee_statistics',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projectemployee', verbose_name='ID Пользователя'),
        ),
        migrations.AlterField(
            model_name='roleemployee',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projectemployee', verbose_name='ID Рабочего'),
        ),
        migrations.AlterField(
            model_name='salary_employee',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projectemployee', verbose_name='ID Рабочего'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projectemployee', verbose_name='ID Рабочего'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projectemployee', verbose_name='ID Рабочего'),
        ),
        migrations.DeleteModel(
            name='Project_employee',
        ),
    ]
