# Generated by Django 4.0.4 on 2022-07-04 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0009_alter_appuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner',
                                       to='main.appuser', verbose_name='ID Создателя'),
        ),
    ]
