# Generated by Django 4.0.4 on 2022-07-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0010_alter_team_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(default='Имя', max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
