# Generated by Django 4.0.4 on 2022-06-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectemployee',
            name='advance',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер аванса'),
        ),
        migrations.AlterField(
            model_name='projectemployee',
            name='salary',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Размер зп, считается автоматически'),
        ),
    ]
