# Generated by Django 4.0.4 on 2022-07-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0011_alter_appuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон пользователя'),
        ),
    ]
