# Generated by Django 4.0.4 on 2022-06-23 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_projectemployee_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectemployee',
            name='role_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='main.role', verbose_name='ID Роли пользователя'),
        ),
        migrations.DeleteModel(
            name='RoleEmployee',
        ),
    ]
