# Generated by Django 4.0.4 on 2022-07-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_projectemployee_assists_work_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectemployee',
            name='assists_work_time',
        ),
        migrations.RemoveField(
            model_name='projectemployee',
            name='interns_work_time',
        ),
        migrations.RemoveField(
            model_name='projectemployee',
            name='masters_work_time',
        ),
        migrations.RemoveField(
            model_name='projectemployee',
            name='mentors_work_time',
        ),
        migrations.RemoveField(
            model_name='projectemployee',
            name='pupils_work_time',
        ),
    ]
