# Generated by Django 4.0.4 on 2022-07-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_projectemployee_assists_work_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assists_work_time',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Суммарное рабочее время всех подсобных проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='interns_work_time',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Суммарное рабочее время всех интернов проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='masters_work_time',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Суммарное рабочее время всех мастеров проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='mentors_work_time',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Суммарное рабочее время всех менторов проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='pupils_work_time',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Суммарное рабочее время всех учеников проекта'),
        ),
    ]
