# Generated by Django 4.0.4 on 2022-06-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_projectemployee_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='project_id',
        ),
    ]
