# Generated by Django 4.0.4 on 2022-07-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_appuser_refresh_token_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='refresh_token_data',
            field=models.TextField(blank=True, null=True, verbose_name='refresh token'),
        ),
    ]
