# Generated by Django 4.0.4 on 2022-06-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0017_remove_timeentry_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_base',
            field=models.BooleanField(blank=True, null=True, verbose_name='Флаг бозовой роли'),
        ),
    ]
