# Generated by Django 4.0.4 on 2022-07-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_appuser_refresh_token_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('date_change', models.DateField(auto_now=True, null=True, verbose_name='Дата внесения изменений')),
                ('income', models.FloatField(blank=True, default=0, null=True, verbose_name='Доход всех работников')),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.project', verbose_name='ID Проекта')),
            ],
            options={
                'verbose_name': 'История проекта',
                'verbose_name_plural': 'Истории проектов',
            },
        ),
        migrations.CreateModel(
            name='HistoryWorker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('date_change', models.DateField(auto_now=True, null=True, verbose_name='Дата внесения изменений')),
                ('salary', models.FloatField(blank=True, default=0, null=True, verbose_name='Размер зп')),
                ('rate', models.FloatField(blank=True, default=0, null=True, verbose_name='Ставка рабочего')),
                ('work_time', models.FloatField(blank=True, default=0, null=True, verbose_name='Суммарное рабочее время')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projectemployee', verbose_name='ID Рабочего')),
            ],
            options={
                'verbose_name': 'История работника',
                'verbose_name_plural': 'Истории работников',
            },
        ),
        migrations.RemoveField(
            model_name='employeestatistics',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='historyrate',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='projectstatistics',
            name='project',
        ),
        migrations.AlterField(
            model_name='historyadvance',
            name='advance',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Размер аванса'),
        ),
        migrations.DeleteModel(
            name='AdvanceStatistics',
        ),
        migrations.DeleteModel(
            name='EmployeeStatistics',
        ),
        migrations.DeleteModel(
            name='HistoryRate',
        ),
        migrations.DeleteModel(
            name='ProjectStatistics',
        ),
    ]
