# Generated by Django 4.0.4 on 2022-07-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_historyproject_historyworker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyadvance',
            name='date_change',
            field=models.DateField(blank=True, null=True, verbose_name='Дата внесения изменений'),
        ),
    ]
