# Generated by Django 4.0.4 on 2022-06-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0018_role_is_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_base',
            field=models.BooleanField(default=False, verbose_name='Флаг бозовой роли'),
        ),
    ]
