# Generated by Django 4.0.4 on 2022-07-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_historyadvance_date_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sum_salary',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Суммарная зп, всех работников'),
        ),
    ]
