# Generated by Django 4.0.4 on 2022-06-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0020_alter_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
