# Generated by Django 4.0.4 on 2022-06-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=254, unique=True, verbose_name='email пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+777', max_length=255, unique=True, verbose_name='Телефон пользователя'),
        ),
    ]
