# Generated by Django 4.0.4 on 2022-07-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_projectemployee_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='refresh_token_data',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='token_data',
        ),
        migrations.CreateModel(
            name='AuthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_data', models.TextField(unique=True, verbose_name='token')),
                ('refresh_token_data', models.TextField(unique=True, verbose_name='refresh token')),
                ('valid_until', models.DateField(verbose_name='Срок годности токена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токены пользователя',
                'verbose_name_plural': 'Токены пользователей',
            },
        ),
    ]
