# Generated by Django 4.0.4 on 2022-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0022_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSocial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name',
                 models.CharField(choices=[('VK', 'ВКонтаке'), ('INSTAGRAM', 'Instagram'), ('TELEGRAM', 'Telegram')],
                                  max_length=15, verbose_name='Название соц.сети')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Связь пользователя и социальной сети',
                'verbose_name_plural': 'Связи пользователей и социальных сетей',
            },
        ),
    ]
