# Generated by Django 4.0.4 on 2022-06-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0023_newsocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_networks',
            field=models.ManyToManyField(to='main.newsocial', verbose_name='Соц. сети пользователя'),
        ),
    ]
