# Generated by Django 4.0.4 on 2022-06-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0024_user_social_networks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsocial',
            options={},
        ),
        migrations.AlterField(
            model_name='newsocial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
