# Generated by Django 4.0.4 on 2022-06-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0025_alter_newsocial_options_alter_newsocial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_networks',
            field=models.ManyToManyField(blank=True, null=True, to='main.newsocial',
                                         verbose_name='Соц. сети пользователя'),
        ),
    ]
